# generated by cabal-rpm-0.11.2
# https://fedoraproject.org/wiki/Packaging:Haskell

%global pkg_name ghc-mod
%global pkgver %{pkg_name}-%{version}

%bcond_with tests

Name:           %{pkg_name}
Version:        5.8.0.0
Release:        2%{?dist}
Summary:        Happy Haskell Hacking

License:        AGPLv3
Url:            https://hackage.haskell.org/package/%{name}
Source0:        https://hackage.haskell.org/package/%{pkgver}/%{pkgver}.tar.gz

BuildRequires:  ghc-Cabal-devel
BuildRequires:  ghc-rpm-macros
# Begin cabal-rpm deps:
BuildRequires:  chrpath
BuildRequires:  ghc-binary-devel
BuildRequires:  ghc-bytestring-devel
BuildRequires:  ghc-cabal-helper-devel
BuildRequires:  ghc-containers-devel
BuildRequires:  ghc-deepseq-devel
BuildRequires:  ghc-directory-devel
BuildRequires:  ghc-djinn-ghc-devel
BuildRequires:  ghc-extra-devel
BuildRequires:  ghc-fclabels-devel
BuildRequires:  ghc-filepath-devel
BuildRequires:  ghc-ghc-boot-devel
BuildRequires:  ghc-ghc-devel
BuildRequires:  ghc-ghc-paths-devel
BuildRequires:  ghc-ghc-syb-utils-devel
BuildRequires:  ghc-haskell-src-exts-devel
BuildRequires:  ghc-hlint-devel
BuildRequires:  ghc-monad-control-devel
BuildRequires:  ghc-monad-journal-devel
BuildRequires:  ghc-mtl-devel
BuildRequires:  ghc-old-time-devel
BuildRequires:  ghc-optparse-applicative-devel
BuildRequires:  ghc-pipes-devel
BuildRequires:  ghc-process-devel
BuildRequires:  ghc-safe-devel
BuildRequires:  ghc-semigroups-devel
BuildRequires:  ghc-split-devel
BuildRequires:  ghc-syb-devel
BuildRequires:  ghc-template-haskell-devel
BuildRequires:  ghc-temporary-devel
BuildRequires:  ghc-text-devel
BuildRequires:  ghc-time-devel
BuildRequires:  ghc-transformers-base-devel
BuildRequires:  ghc-transformers-devel
%if %{with tests}
BuildRequires:  ghc-doctest-devel
BuildRequires:  ghc-hspec-devel
%endif
# End cabal-rpm deps

%description
Ghc-mod is a backend program to enrich Haskell programming in editors.
It strives to offer most of the features one has come to expect from modern
IDEs in any editor. ghc-mod provides a library for other haskell programs to
use as well as a standalone program for easy editor integration. All of the
fundamental functionality of the frontend program can be accessed through the
library however many implementation details are hidden and if you want to
significantly extend ghc-mod you should submit these changes upstream instead
of implementing them on top of the library.


%package -n ghc-%{name}
Summary:        Haskell %{name} library

%description -n ghc-%{name}
This package provides the Haskell %{name} shared library.


%package -n ghc-%{name}-devel
Summary:        Haskell %{name} library development files
Provides:       ghc-%{name}-static = %{version}-%{release}
Requires:       ghc-compiler = %{ghc_version}
Requires(post): ghc-compiler = %{ghc_version}
Requires(postun): ghc-compiler = %{ghc_version}
Requires:       ghc-%{name}%{?_isa} = %{version}-%{release}

%description -n ghc-%{name}-devel
This package provides the Haskell %{name} library development files.


%prep
%setup -q

# monad-journal 0.8 removes the instance of EitherT, which ghc-mod does not use
cabal-tweak-dep-ver monad-journal '< 0.8' '< 0.9'


%build
%ghc_lib_build


%install
%ghc_lib_install
%ghc_fix_rpath %{pkgver}


%check
%cabal_test


%post -n ghc-%{name}-devel
%ghc_pkg_recache


%postun -n ghc-%{name}-devel
%ghc_pkg_recache


%files
%license COPYING.BSD3
%license COPYING.AGPL3
%doc ChangeLog README.md
%{_bindir}/%{name}
%{_bindir}/ghc-modi


%files -n ghc-%{name} -f ghc-%{name}.files
%license COPYING.BSD3
%license COPYING.AGPL3
%{_datadir}/%{pkgver}


%files -n ghc-%{name}-devel -f ghc-%{name}-devel.files
%doc ChangeLog README.md


%changelog
* Fri Jan 26 2018 David Shea <dshea@redhat.com> - 5.8.0.0-2
- Rebuild for new hlint

* Thu Dec  7 2017 Fedora Haskell SIG <haskell@lists.fedoraproject.org> - 5.8.0.0-1
- spec file generated by cabal-rpm-0.11.2
