# generated by cabal-rpm-0.11.2
# https://fedoraproject.org/wiki/Packaging:Haskell

%global pkg_name utility-ht
%global pkgver %{pkg_name}-%{version}

%bcond_without tests

Name:           ghc-%{pkg_name}
Version:        0.0.14
Release:        1%{?dist}
Summary:        Various small helper functions for Lists, Maybes, Tuples, Functions

License:        BSD
Url:            https://hackage.haskell.org/package/%{pkg_name}
Source0:        https://hackage.haskell.org/package/%{pkgver}/%{pkgver}.tar.gz

BuildRequires:  ghc-Cabal-devel
BuildRequires:  ghc-rpm-macros
# Begin cabal-rpm deps:
%if %{with tests}
BuildRequires:  ghc-QuickCheck-devel
%endif
# End cabal-rpm deps

%description
Various small helper functions for Lists, Maybes, Tuples, Functions.
Some of these functions are improved implementations of standard functions.
They have the same name as their standard counterparts. Others are equivalent
to functions from the 'base' package, but if you import them from this utility
package then you can write code that runs on older GHC versions or other
compilers like Hugs and JHC.

All modules are plain Haskell 98. The package depends exclusively on the 'base'
package and only that portions of 'base' that are simple to port. Thus you do
not risk a dependency avalanche by importing it. However, further splitting the
base package might invalidate this statement.

Alternative packages: 'Useful', 'MissingH'.


%package devel
Summary:        Haskell %{pkg_name} library development files
Provides:       %{name}-static = %{version}-%{release}
Requires:       ghc-compiler = %{ghc_version}
Requires(post): ghc-compiler = %{ghc_version}
Requires(postun): ghc-compiler = %{ghc_version}
Requires:       %{name}%{?_isa} = %{version}-%{release}

%description devel
This package provides the Haskell %{pkg_name} library development files.


%prep
%setup -q -n %{pkgver}


%build
%ghc_lib_build


%install
%ghc_lib_install


%check
%cabal_test


%post devel
%ghc_pkg_recache


%postun devel
%ghc_pkg_recache


%files -f %{name}.files
%license LICENSE


%files devel -f %{name}-devel.files


%changelog
* Mon Dec  4 2017 Fedora Haskell SIG <haskell@lists.fedoraproject.org> - 0.0.14-1
- spec file generated by cabal-rpm-0.11.2
